---
###############################################################################
# Interfaces.d (Local Configuration)
###############################################################################
# Configure local interfaces options.
#
# Args:
#   service: str - Name of local config (/etc/network/interfaces.d/{NAME}).
#   state: str - Whether config should be present or absent.
#   config: str - Network interface config, see defaults.yml.
#
# Reference:
# * https://manpages.debian.org/bookworm/ifupdown2/interfaces.5.en.html

- name: 'Interfaces.d | remove local config {{ service }}'
  when: state | lower == 'absent'
  notify: 'Handlers | reload restart networking'
  ansible.builtin.file:
    path: '/etc/network/interfaces.d/{{ service }}'
    state: 'absent'

- name: 'Interfaces.d | set local config {{ service }}'
  when: state | lower == 'present'
  notify: 'Handlers | reload restart networking'
  ansible.builtin.template:
    src: 'local.j2'
    dest: '/etc/network/interfaces.d/{{ service }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
