---
# yamllint disable rule:line-length
###############################################################################
# Configure global network interfaces.
###############################################################################
# WARNING: for Proxmox/LXC containers, the network configuration **must** be
# set in the LXC container configuration. Changing from DHCP (set in PVE) to
# static (set in the LXC container) will cause network connection failures.
#
# Setting both network definitions will prefer manual configuration.
#
# Network device definition using /etc/network/interfaces format.
#
# Proxmox must define all network interfaces here in order for the WebUI and
# SDN to detect settings (trigger ifreload -a to force refresh in Proxmox 8).
# Reboot instead of using os_optimizations_systemctl_network_restart.
#
# Default: '' (un-managed).
#
# Reference:
# * https://forum.proxmox.com/threads/how-to-edit-etc-network-interfaces-with-ansible-correctly.130972/
# yamllint enable rule:line-length

- name: 'Network | interfaces | assert interfaces defined for interfaces.d'
  when: network_interfaces_source_enable
  ansible.builtin.assert:
    quiet: true
    that:
      - 'network_local | length > 0'
    fail_msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │            network_local must have defined interfaces.            │
      │                                                                   │
      ├───────────────────────────────────────────────────────────────────╯
      │ network_local must have defined interfaces if
      │ network_interfaces_source_enable.
      │
      │ Otherwise ifreload and post-up will fail.

- name: 'Network | interfaces | set'
  when: network_interfaces | length > 0
  notify: 'Handlers | reload restart networking'
  ansible.builtin.template:
    src: 'interfaces.j2'
    dest: '/etc/network/interfaces'
    owner: 'root'
    group: 'root'
    mode: '0644'
    force: true
