---
- name: 'Prep'
  ansible.builtin.import_tasks: 'prep.yml'

- name: 'TCP BBR'
  when: not network_flg_container
  ansible.builtin.import_tasks: 'tcp_bbr.yml'

- name: 'IPv4'
  when: not network_flg_container
  ansible.builtin.import_tasks: 'ip_v4.yml'

- name: 'IPv6'
  when: not network_flg_container
  ansible.builtin.import_tasks: 'ip_v6.yml'

- name: 'Resolv'
  ansible.builtin.import_tasks: 'resolv.yml'

- name: 'FRR'
  when: network_flg_frr
  ansible.builtin.import_tasks: 'frr.yml'

- name: 'Interfaces'
  ansible.builtin.import_tasks: 'interfaces.yml'

- name: 'Interfaces.d'
  ansible.builtin.include_tasks: 'interfaces_d.yml'
  when: network_cfg_local | length > 0
  vars:
    service: '{{ local.service }}'
    state: '{{ local.state | default("present") }}'
    config: '{{ local.config }}'
  loop: '{{ network_cfg_local }}'
  loop_control:
    loop_var: 'local'
    label: '{{ local.service }}'
