---
###############################################################################
# Network Handlers
###############################################################################

- name: 'Handlers | ifreload'
  listen:
    - 'Handlers | ifreload networking'
    - 'Handlers | ifreload FRR'
  ansible.builtin.command: '/usr/sbin/ifreload -a'
  become: true
  changed_when: false

- name: 'Handlers | networking'
  listen: 'Handlers | ifreload networking'
  when: network_srv_systemctl_network_restart
  ansible.builtin.systemd:
    name: 'networking'
    state: 'restarted'
  changed_when: true

- name: 'Handlers | FRR'
  listen: 'Handlers | ifreload FRR'
  ansible.builtin.systemd:
    name: 'frr'
    state: 'restarted'
