---
# yamllint disable rule:line-length
- name: 'Default | verify | test sysctl | query {{ item.name }}'  # noqa syntax-check[specific] not a play
  ansible.builtin.command: 'sysctl --values {{ item.name }}'
  register: _test_network_sysctl
  changed_when: false

- name: 'Default | verify | test sysctl | assert {{ item.name }}={{ item.value }}'
  ansible.builtin.assert:
    that:
      - _test_network_sysctl.stdout == item.value
    fail_msg: >
      sysctl should report {{ item.name }}={{ item.value }}
      ({{ _test_network_sysctl.stdout }}).
