---
- name: 'Default | verify'
  hosts: 'all'
  gather_facts: false
  become: true
  tasks:
    - name: 'Default | verify | /etc/resolv.conf'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Default | verify | /etc/resolv.conf'
        test_src: '/etc/resolv.conf.ansible'
        test_remote_src: true
        test_file: '/etc/resolv.conf'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'

    - name: 'Default | verify | /etc/network/interfaces'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Default | verify | /etc/network/interfaces'
        test_src: '/etc/network/interfaces.ansible'
        test_remote_src: true
        test_file: '/etc/network/interfaces'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'

    - name: 'Default | verify | sysctl'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'sysctl.yml'
      vars:
        test_name: 'Default | verify | sysctl | {{ item.name }}'
        test_option: '{{ item.name }}'
        test_value: '{{ item.value }}'
      loop:
        - {name: 'net.ipv4.tcp_congestion_control', value: 'bbr'}
        - {name: 'net.ipv4.conf.all.forwarding', value: '0'}
        - {name: 'net.ipv4.conf.default.forwarding', value: '0'}
        - {name: 'net.ipv6.conf.all.forwarding', value: '0'}
        - {name: 'net.ipv6.conf.default.forwarding', value: '0'}
        - {name: 'net.ipv6.conf.all.disable_ipv6', value: '1'}
        - {name: 'net.ipv6.conf.default.disable_ipv6', value: '1'}
        - {name: 'net.ipv6.conf.lo.disable_ipv6', value: '1'}
      loop_control:
        label: '{{ item.name }}'
