---
###############################################################################
# Converge
###############################################################################
# Inject vagrant network blocks.
#
# Args:
#   _test_network_vagrant: str - vagrant network blocks.

- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  become: true
  tasks:
    - name: 'Converge | assert fact_caching not expired'
      ansible.builtin.assert:
        quiet: true
        that:
          - '_test_network_vagrant is defined'
        fail_msg: |
          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │             fact_caching has expired; re-run prepare.             │
          │                                                                   │
          ╰───────────────────────────────────────────────────────────────────╯

    - name: 'Converge | run r_pufky.deb.network'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.network'
      vars:
        network_interfaces: '{{ _test_network_vagrant }}'
