---
# Args:
#   _test_network_vagrant: str - vagrant network block
- name: 'FRR | converge'
  hosts: 'all'
  gather_facts: false
  become: true
  tasks:
    - name: 'FRR | converge | assert fact_caching not expired'
      ansible.builtin.assert:
        that:
          - '_test_network_vagrant is defined'
        fail_msg: 'fact_caching has expired; re-run prepare.'

    - name: 'FRR | converge | run r_pufky.srv.network'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.network'
      vars:
        network_interfaces: '{{ _test_network_vagrant }}'
