---
###############################################################################
# FRR
###############################################################################
# Network level testing requires VMs for kernel namespace and systemd
# networking without affecting host. Test base role applies correctly.
#
# Tests:
# * /etc/network/interfaces FRR service restart before/after sources.
# * FRR is enabled, active with fabricd running.

dependency:
  name: 'galaxy'
driver:
  name: 'vagrant'
  provider:
    name: 'libvirt'
    type: 'libvirt'
provisioner:
  name: 'ansible'
  connection_options:
    ansible_ssh_user: 'vagrant'
    ansible_become: true
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
      fact_caching: 'jsonfile'  # cache vagrant VM network configuration.
      fact_caching_connection: '/tmp/facts_cache'
      fact_caching_timeout: 7200
  inventory:
    group_vars:
      all:
        apt_srv_auto_grub_boot: true  # Testing VM only.
        network_flg_frr: true
        network_frr_config: |
         frr defaults traditional
         hostname test_frr_host
         log syslog warning
         ip forwarding
         no ipv6 forwarding
         service integrated-vtysh-config
         !
         interface lo
          ip address 10.11.11.{XX}/32
          ip router openfabric 1
          openfabric passive
         interface eth0
          ip router openfabric 1
          openfabric csnp-interval 2
          openfabric hello-interval 1
          openfabric hello-multiplier 2
         !
         line vty
         !
         router openfabric 1
          net 49.0011.0010.1111.00{XX}.00
          lsp-gen-interval 1
          max-lsp-lifetime 600
          lsp-refresh-interval 180
    host_vars:
      network-frr-disable-mgmt:
        network_cfg_interfaces_source_enable: false
        network_frr_interfaces_enable: false
        network_frr_config: 'log syslog informational'
      network-frr-enable-src:
        network_cfg_interfaces_source_enable: true
        network_frr_interfaces_enable: true
        network_frr_daemon_fabricd_enable: true
        network_cfg_local:
          - service: 'test_adapter'
            state: 'present'
            config: |
              # allow-hotplug enp15s0f10
              # iface enp15s0f10 inet manual
              # test network adapter loaded from interfaces.d
      network-frr-enable-nosrc:
        network_cfg_interfaces_source_enable: false
        network_frr_interfaces_enable: true
        network_frr_daemon_fabricd_enable: true
platforms:
  - name: 'network-frr-disable-mgmt'
    box: 'debian/trixie64'
    memory: 4096
    cpus: 2
    interfaces:
      - network_name: 'private_network'
        auto_config: true
        type: 'dhcp'
  - name: 'network-frr-enable-src'
    box: 'debian/trixie64'
    memory: 4096
    cpus: 2
    interfaces:
      - network_name: 'private_network'
        auto_config: true
        type: 'dhcp'
  - name: 'network-frr-enable-nosrc'
    box: 'debian/trixie64'
    memory: 4096
    cpus: 2
    interfaces:
      - network_name: 'private_network'
        auto_config: true
        type: 'dhcp'
verifier:
  name: 'ansible'
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'verify'
    - 'destroy'
