---
###############################################################################
# FRR
###############################################################################
# Network level testing requires VMs for kernel namespace and systemd
# networking without affecting host. Test base role applies correctly.
#
# Tests:
# * /etc/network/interfaces FRR service restart before/after sources.
# * FRR is enabled, active with fabricd running.

dependency:
  name: 'galaxy'
driver:
  name: 'vagrant'
  provider:
    name: 'virtualbox'
    config_options:
      ssh.keep_alive: true
      ssh.remote_user: 'root'
    options:
      append_platform_to_hostname: false
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
      fact_caching: 'jsonfile'  # cache vagrant VM network configuration
      fact_caching_connection: '/tmp/facts_cache'
      fact_caching_timeout: 7200
  inventory:
    group_vars:
      all:
        network_frr_enable: true
        network_frr_config: |
         frr defaults traditional
         hostname test_frr_host
         log syslog warning
         ip forwarding
         no ipv6 forwarding
         service integrated-vtysh-config
         !
         interface lo
          ip address 10.11.11.{XX}/32
          ip router openfabric 1
          openfabric passive
         interface eth0
          ip router openfabric 1
          openfabric csnp-interval 2
          openfabric hello-interval 1
          openfabric hello-multiplier 2
         !
         line vty
         !
         router openfabric 1
          net 49.0011.0010.1111.00{XX}.00
          lsp-gen-interval 1
          max-lsp-lifetime 600
          lsp-refresh-interval 180
    host_vars:
      network-debian-13-vm-frr-disable-management:
        network_interfaces_source_enable: false
        network_frr_interfaces_enable: false
        network_frr_config: 'log syslog informational'
      network-debian-13-vm-frr-enable-with-sources:
        network_interfaces_source_enable: true
        network_frr_interfaces_enable: true
        network_frr_daemon_fabricd_enable: true
        network_local:
          - service: 'test_adapter'
            state: 'present'
            config: |
              # allow-hotplug enp15s0f10
              # iface enp15s0f10 inet manual
              # test network adapter loaded from interfaces.d
      network-debian-13-vm-frr-enable-no-sources:
        network_interfaces_source_enable: false
        network_frr_interfaces_enable: true
        network_frr_daemon_fabricd_enable: true
platforms:
  - name: 'network-debian-13-vm-frr-disable-management'
    # TODO(role): switch to debian/trixie64 when released.
    box: 'debian/testing64'
    memory: 4096
    cpus: 2
    interfaces:
      - network_name: private_network  # network_name required
        auto_config: true
        type: 'dhcp'
  - name: 'network-debian-13-vm-frr-enable-with-sources'
    # TODO(role): switch to debian/trixie64 when released.
    box: 'debian/testing64'
    memory: 4096
    cpus: 2
    interfaces:
      - network_name: private_network  # network_name required
        auto_config: true
        type: 'dhcp'
  - name: 'network-debian-13-vm-frr-enable-no-sources'
    # TODO(role): switch to debian/trixie64 when released.
    box: 'debian/testing64'
    memory: 4096
    cpus: 2
    interfaces:
      - network_name: private_network  # network_name required
        auto_config: true
        type: 'dhcp'
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    # - 'idempotence'  # setting immutable can only be done once.
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
