---
###############################################################################
# Converge
###############################################################################
# Inject vagrant network blocks.
#
# Args:
#   network__test_vagrant: str - vagrant network block.
#   network__test_resolv: str - resolv.conf block.

- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  become: true
  tasks:
    - name: 'Converge | assert | fact_caching not expired'
      ansible.builtin.assert:
        quiet: true
        that:
          - ansible_facts['network__test_resolv'] is defined
          - ansible_facts['network__test_vagrant'] is defined
        fail_msg: |

          ✘ fact_caching has expired; re-run prepare.

    - name: 'Converge | role | r_pufky.deb.network'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.network'
      vars:
        network_cfg_resolv: |
          {{ ansible_facts['network__test_resolv'] }}
          # vm_network custom resolv.conf modification test.
        network_cfg_interfaces: '{{ ansible_facts["network__test_vagrant"] }}'
