---
###############################################################################
# Interfaces Resolv
###############################################################################
# Network level testing requires VMs for kernel namespace and systemd
# networking without affecting host. Test base role applies correctly.
#
# Tests:
# * /etc/network/interfaces with defaults applied correctly with IPv6 enabled.
# * /etc/resolv.conf written correctly.

dependency:
  name: 'galaxy'
driver:
  name: 'vagrant'
  provider:
    name: 'libvirt'
    type: 'libvirt'
provisioner:
  name: 'ansible'
  connection_options:
    ansible_ssh_user: 'vagrant'
    ansible_become: true
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
      fact_caching: 'jsonfile'  # cache vagrant VM network configuration.
      fact_caching_connection: '/tmp/facts_cache'
      fact_caching_timeout: 7200
  inventory:
    group_vars:
      all:
        network_srv_ipv6: true
        network_cfg_interfaces_source_enable: true
        network_cfg_local:
          - service: 'test_adapter'
            state: 'present'
            config: |
              # allow-hotplug enp15s0f10
              # iface enp15s0f10 inet manual
              # test network adapter loaded from interfaces.d
platforms:
  - name: 'network-interfaces-resolv'
    box: 'debian/trixie64'
    memory: 4096
    cpus: 2
    interfaces:
      - network_name: 'private_network'
        auto_config: true
        type: 'dhcp'
verifier:
  name: 'ansible'
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'verify'
    - 'destroy'
