---
###############################################################################
# Verify
###############################################################################
# Verify resolv configuration is correct using cached dynamic vagrant blocks.
#
# Args:
#   _test_network_vagrant: str - vagrant network block.
#   _test_network_resolv: str - resolv.conf block.

- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  become: true
  tasks:
    - name: 'Verify | assert fact_caching not expired'
      ansible.builtin.assert:
        quiet: true
        that:
          - '_test_network_resolv is defined'
          - '_test_network_vagrant is defined'
        fail_msg: |
          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │             fact_caching has expired; re-run prepare.             │
          │                                                                   │
          ╰───────────────────────────────────────────────────────────────────╯

    - name: 'Verify | /etc/resolv.conf'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'template.yml'
      vars:
        test_name: 'Verify | /etc/resolv.conf'
        test_src: 'template.j2'
        test_file: '/etc/resolv.conf'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
        test_diff: true
        test_content: |
          {{ _test_network_resolv }}
          # vm_network custom resolv.conf modification test.

    - name: 'Verify | /etc/network/interfaces'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'template.yml'
      vars:
        test_name: 'Verify | /etc/network/interfaces'
        test_src: 'template.j2'
        test_file: '/etc/network/interfaces'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
        test_diff: true
        test_content: |
          # This file describes the network interfaces available on your system
          # and how to activate them. For more information, see interfaces(5).

          {{ _test_network_vagrant }}
          source /etc/network/interfaces.d/*

    - name: 'Verify | interfaces | /etc/network/interfaces.d/test_adapter'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: >
          Verify | interfaces |
          /etc/network/interfaces.d/test_adapter
        test_src: 'test_adapter'
        test_file: '/etc/network/interfaces.d/test_adapter'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'

    - name: 'Verify | interfaces | get IPv6 status'
      ansible.builtin.command: 'sysctl --values net.ipv6.conf.all.disable_ipv6'
      register: _test_network_ipv6
      changed_when: false

    - name: 'Verify | interfaces | assert IPv6 enabled'
      ansible.builtin.assert:
        quiet: true
        that:
          - _test_network_ipv6.stdout | int == 0
        fail_msg: |
          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │       sysctl should report net.ipv6.conf.all.disable_ipv6=0       │
          │                                                                   │
          ├───────────────────────────────────────────────────────────────────╯
          │ {{ _test_network_ipv6.stdout }}
