---
# Network level testing requires VMs for kernel namespace and systemd
# networking without affecting host. Test /etc/network configurations are
# applied correctly with IPv6 enabled.
#
# As network information may be dynamic per the VM instance when it is spun up,
# copy the current network configuration and inject known settings to validate
# that the files were written correctly.

dependency:
  name: 'galaxy'
driver:
  name: 'vagrant'
  provider:
    name: 'virtualbox'
    config_options:
      ssh.keep_alive: true
      ssh.remote_user: 'root'
    options:
      append_platform_to_hostname: false
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
  inventory:
    group_vars:
      all:
        network_ipv6_enable: true
        network_local:
          - service: 'test_adapter'
            state: 'present'
            config: |
              # allow-hotplug enp15s0f10
              # iface enp15s0f10 inet manual
              # test network adapter loaded from interfaces.d
platforms:
  - name: 'network-debian-12-vm-network'
    box: 'debian/bookworm64'
    memory: 4096
    cpus: 2
    interfaces:
      - network_name: private_network  # network_name required
        auto_config: true
        type: 'dhcp'
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    # - 'idempotence'  # setting immutable can only be done once.
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
