---
# yamllint disable rule:line-length
- name: 'Network | prepare'
  hosts: 'all'
  gather_facts: false
  become: true
  tasks:
    - name: 'Network | prepare | get /etc/resolv.conf'
      ansible.builtin.copy:
        src: '/etc/resolv.conf'
        remote_src: true
        dest: '/etc/resolv.conf.ansible'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: 'Network | prepare | set dynamic expected results for /etc/resolv.conf'
      ansible.builtin.lineinfile:
        path: '/etc/resolv.conf.ansible'
        line: '# vm_network custom resolv.conf modification test.'

    # ifreload only supports sources, not source-directory.
    - name: 'Network | prepare | set sources instead of source-directory'
      ansible.builtin.lineinfile:
        path: '/etc/network/interfaces'
        regexp: '^source-directory(.*)$'
        line: 'source /etc/network/interfaces.d/*'

    - name: 'Network | prepare | get /etc/network/interfaces'
      ansible.builtin.slurp:
        path: '/etc/network/interfaces'
      register: _test_network_interfaces

    - name: 'Network | prepare | set pre-test expected /etc/network/interfaces'
      ansible.builtin.copy:
        dest: '/etc/network/interfaces.pre_test.ansible'
        owner: 'root'
        group: 'root'
        mode: '0644'
        # from templates/interfaces.j2
        content: '{{ _test_network_interfaces.content | b64decode }}'

    - name: 'Network | prepare | set post-test expected /etc/network/interfaces'
      ansible.builtin.copy:
        dest: '/etc/network/interfaces.post_test.ansible'
        owner: 'root'
        group: 'root'
        mode: '0644'
        # from templates/interfaces.j2
        content: |
          # This file describes the network interfaces available on your system
          # and how to activate them. For more information, see interfaces(5).

          {{ _test_network_interfaces.content | b64decode }}
