---
# yamllint disable rule:line-length
# TODO(role): add _test_network_* to fail_msg when diff support fixed for
#     remote files.
#
# Reference:
# * https://github.com/ansible/ansible/issues/84309
# * https://github.com/ansible/ansible/issues/66983
- name: 'Network | verify'
  hosts: 'all'
  gather_facts: false
  become: true
  tasks:
    - name: 'Network | verify | query /etc/resolv.conf'
      ansible.builtin.copy:
        src: '/etc/resolv.conf.ansible'
        remote_src: true
        dest: '/etc/resolv.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'
      check_mode: true
      diff: true
      register: _test_network_resolv

    - name: 'Network | verify | assert expected /etc/resolv.conf'
      ansible.builtin.assert:
        that:
          - not _test_network_resolv.changed
        fail_msg: >
          /etc/resolv.conf is not in expected format.

    - name: 'Network | verify | query /etc/network/interfaces'
      ansible.builtin.copy:
        src: '/etc/network/interfaces.post_test.ansible'
        remote_src: true
        dest: '/etc/network/interfaces'
        owner: 'root'
        group: 'root'
        mode: '0644'
      check_mode: true
      diff: true
      register: _test_network_interfaces

    - name: 'Network | verify | assert expected /etc/network/interfaces'
      ansible.builtin.assert:
        that:
          - not _test_network_interfaces.changed
        fail_msg: >
          /etc/network/interfaces is not in expected format.

    - name: 'Network | verify | query /etc/network/interfaces.d/test_adapter'
      ansible.builtin.copy:
        src: 'files/test_adapter'
        dest: '/etc/network/interfaces.d/test_adapter'
        owner: 'root'
        group: 'root'
        mode: '0644'
      check_mode: true
      diff: true
      register: _test_network_interfaces_d

    - name: 'Network | verify | assert expected /etc/network/interfaces.d/test_adapter'
      ansible.builtin.assert:
        that:
          - not _test_network_interfaces_d.changed
        fail_msg: >
          /etc/network/interfaces.d/test_adapter is not in expected format:
          {{ _test_network_interfaces_d.diff }}.

    - name: 'Network | verify | get IPv6 status'
      ansible.builtin.command: 'sysctl --values net.ipv6.conf.all.disable_ipv6'
      register: _test_network_ipv6
      changed_when: false

    - name: 'Network | verify | assert IPv6 enabled'
      ansible.builtin.assert:
        that:
          - _test_network_ipv6.stdout | int == 0
        fail_msg: >
          sysctl should report net.ipv6.conf.all.disable_ipv6=0
          ({{ _test_network_ipv6.stdout }}).
